- name: Example Docker Playbook
  hosts: all
  hosts: ./
  tasks:
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: Build Docker Image
      command: docker build -t calculator.jar .

    - name: tag image
      command: docker tag calculator.jar lavish11/calculator:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "lavish11"
        password: "Lavish@123"

    - name: Push image
      command: docker push lavish11/calculator:latest