---
- name: Example Docker Playbook
  hosts: localhost
  remote_user: ubuntu
  vars:
    ansible_python_interpreter: /home/ubuntu/.local/lib/python3.10/site-packages
  tasks:
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Build Docker Image
      command: docker build -t calculator.jar .

    - name: Tag image
      command: docker tag calculator.jar lavish11/calculator:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "lavish11"
        password: "Lavish@123"

    - name: Push image
      command: docker push lavish11/calculator:latest
