---
- name: Example Docker Playbook
  hosts: localhost
  remote_user: ubuntu

  tasks:
    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes  # Elevate privileges for this task

    - name: Build Docker Image
      command: docker build -t calculator.jar .
      become: yes  # Elevate privileges for this task

    - name: Tag image
      command: docker tag calculator.jar lavish11/calculator:latest
      become: yes  # Elevate privileges for this task

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "lavish11"
        password: "Lavish@123"
      become: yes  # Elevate privileges for this task

    - name: Push image
      command: docker push lavish11/calculator:latest
      become: yes  # Elevate privileges for this task
